= vm-dev
A Virtual Machine for fullstack development. 

This Vagrant configuration comes with a set of open-source predefined tools for a typical fullstack stack, including Java/Spring on the backend and ECMAScript on the frontend.

To allow incremental validation before upgrading and avoiding tools regressions or unexpected incompatibilities, we use version-pinned packages when possible.

It includes:

- **IDEs**: IntelliJ IDEA Community Edition, VSCode, VIM, Geany
- **VCS**: Git
- **Integration**: Docker CE, K3S (Kubernetes), k9s
- **Testing tools**: Bruno
- **Performance tools**: JVisualVM, MAT, JMeter
- **Database tools**: DBeaver, Pgbadger
- **VM**: Guest Additions

== Prerequisites

=== To build a VirtualBox VM
* https://developer.hashicorp.com/vagrant/install?product_intent=vagrant[Install] a recent Vagrant distribution.

WARNING: As of October 2024, Vagrant does not yet support VirtualBox 7.1. Use VB 7 from https://www.virtualbox.org/wiki/Download_Old_Builds_7_0[here].

=== To run the VM

* A Linux / Windows / Mac OS machine with 16 GB+ RAM (for actual fullstack autonomous development, aim for 32 GiB+).
* A recent (7+) https://www.virtualbox.org/wiki/Downloads[VirtualBox installation] with the associated extension pack. Note that you don't have to install VirtualBox guest additions into the VM, as they are already included in the Vagrant image.

TIP: The Oracle Extension Pack is not required to build or run this VM unless you plan to encrypt the virtual disks.

TIP: Prefer lightweight hosts and stop as many host programs as possible to free memory for your VM. I recommend using an XFCE-based Debian host.

TIP: For corporate development, especially if the VM is not stored on an encrypted disk (such as a full disk encryption (FDE) disk), we strongly recommend encrypting the virtual disks.

== How to build an image?

* Search for `[CUSTOM]` comments; they indicate places to customize or extend this VM.
* This image is primarily preset for a French-based locale, which you can change in the Vagrant file.

== Customization by the end user of the image

* Customize and launch the `post-install-as-user.sh` script as the `vagrant` user.
* Change the `vagrant` password.


== Use the VM

* Connect with `vagrant`/`vagrant` (change the password). `Vagrant` is a sudoer.
* Prefer shutting down from the VM. Shutting down directly from the VirtualBox menu is like a power failure and can corrupt the filesystem.

== Troubleshooting

TIP: Check performance logs in `/var/log/atop`.
